sudo: true
dist: trusty
language: node_js
node_js:
  - "7"
before_script:
  - sudo add-apt-repository -y ppa:mozillateam/firefox-next
  - sudo apt-get update
  - sudo apt-get install -y firefox
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
