dist: trusty

language: node_js

node_js:
  - "6"

addons:
  sauce_connect: true

env:
  global:
    - secure: bMl2I0syLl1sSMl63icwoghOvE841SCsUtND7jJH6HItKmhyudmmw2fC+7bi/EiChpSv9FbXpmEpchmXBShv41pqjXYZznHMeiMAGf8d683rzHXfmBgu9mt5TpuZ3qzXPh3c+dHOwlZeusQEeqVonoerxfL6tdQiXZZsGRlheY8dKZNsnQMFai57MWJqEzVLofThgOyaenEHxkp/zT35zjpPy3uBgdWs/8yrXMnRcU1Ya3fCssEnePNL6BDgIZPzum0oo3hB+kKGkvkC8bItXm1xXgrZI7GEO7vT/OeYgvlPRE8wxZbSSt+lrpLkRw332N+XwxKqpCB9RDLc291DvYSrhM3S5NFGa4XsBnBVcVpcHC1cEpvtiFUFmMFpUSx9rqoBXQ7sU1CtL3yi+RH1fM1AOdBfgmVGV8nF5v7UCX5sAmpXI2FJaB51hY1t++ZtmljXp33Ym5sAZYKFXgoCeg2vmeoushKITLi9/rLmoUfG5ZqZ6yVg77YmQuce9S2sVXq6RtgdT1Vu/a2TM65uR+3WklsUNGGat6AxzOGVGpmo2pitAmlcncTuNeHFyhIuXJKFm0Xo+pzXdBMxkpbM+HuHu4Y2dR28phCGuf7uAsrWi+tQAnsXIkKYjvpty0IESyf3SOxwYjf4AQPcVyuAgSjMQq1ewsUHtZXdITDXijM=
    - secure: ZIwJbP8DOvn6a1TbwcT1dTMUVNtuOhgUT08ydYAdPAPLl/yQUunY5BtXgmR302GWb6Dn55VCPe9P+nfcFsDBdNjypMw2Ah4cQkTYyDk+iRO6HxtP4IYbm8AZ7B8uvbPd8j1dvvxOShlcFfzBNWzG8P1NbnqLMUPKapBH3zZiJztmFaYBWXSJqIu2yERkJvkOFd0IDdjedbfWYR5/R0AcwepEuybSpJEUmX/aV3LcZHQmZcS72M0OyAgCExbJV9yF7nWg0H44rStNJVGExpfidZJWTNfyzJaXx5ofFwWkp6S5BjjFSe2e1CDn1pMrh0BnV2kqEXVgr6Ui+0HXVdfIIKZiZ/hp8KygfUp+my9FD/lufMy/BeF/MBekJJW+JO15cXxi7hoxg5v1ZEiwKXc+o89W+cr8xX+jzUMPUKS4ZelT7KiD2pSrSZJt2oxZGpF7Op5eQcTMhIuDh2fECDpb+MXRwf+9/Nqzr1aavm5e6kRZFw3xTehP2eKcb7nGGfw6nC73SXzWRF5BgeyFVanV88u7waQbx2LVXLlrRAG3WlrW1aNDBx9Oe2NGHwImsDT8qwb008lqLo39JTIWIncm+zC4xAi9MK/r5iXIO2pLIIoxvYO50wRIfUuodhVa31x1LVmMiUfNVs0drED6FhTaaf52VMzMnCVhGiBovnTaUB4=

script: npm test -- --port 4445
